### ISSUE TITLE
Strange return slice content

### ISSUE THREAD

**Issue by pharrisee** [technicalviking/tulipindicators#5]
Not sure if this is an actual bug, or just a misunderstanding on my part, but, given this data (taken from this page https://tulipindicators.org/adosc), but I'm not sure the data is actually part of the issue :

high: ```[]float64{82.15,81.89,83.03,83.30,83.85,83.90,83.33,84.30,84.84,85.00,85.90,86.58,86.98,88.00,87.87}```
low: ```[]float64{81.29,80.64,81.31,82.65,83.07,83.11,82.49,82.30,84.15,84.11,84.03,85.39,85.76,87.17,87.01}```
close: ```[]float64{81.59,81.06,82.87,83.00,83.61,83.15,82.84,83.99,84.55,84.36,85.53,86.54,86.89,87.77,87.2}```
volume: ```[]float64{5653100.00,6447400.00,7690900.00,3831400.00,4455100.00,3798000.00,3936200.00,4732000.00,4841300.00,3915300.00,6830800.00,6694100.00,5293600.00,7985800.00,4807900.00}```
short period: 2
long period: 5

and running that with:

```
output, err := tulip.Indicators["adosc"](
		[][]float64{
			high,
			low,
			close,
			volume,
		},
		[]float64{
			2.0,
			5.0,
		},
	)
```

The actual output array is:

```
[][]float64{
  {1900759.847346,
  399262.039520,
  -241806.815445,
  757828.286883,
  1068830.284519,
  328526.245735,
  1466909.295997,
  0.000000,
  0.000000,
  0.000000,
  0.000000,
},
}
```
 (notice the zero entries at the end)

The documentation on this page, https://tulipindicators.org/adosc, seems to suggest that the output should be:

```
[][]float64{
  {0.000000,
  0.000000,
  0.000000,
  0.000000,
  1900759.850000,
  399262.040000,
  -241806.820000,
  757828.290000,
  1068830.290000,
  328526.250000,
  1466909.300000,
  3475262.290000,
  4653474.790000,
  5067839.270000,
  3474675.620000}
}
```

which I think makes more sense, since the first 4 entries would be zero as there wouldn't be enough data for any successful calculation. Obvious differences with rounding aside of course.

This issue doesn't only affect adosc, I've tried a few different indicators which require 'warmup' and have seen the same behaviour on all of the ones tried so far.

Any ideas?  Is this a bug?  Am I misunderstanding the returned data? Am I misunderstanding the input data, should it be sorted earliest first, or latest first?

**Comment by Code-exE-Software** [comment]
I feel the documentation is a little misleading here, unless taken in
context with the documentation here:
https://tulipindicators.org/usage#interface

My plugin somewhat obfuscates the need to explicitly know the difference in
sizes between the input length and the output, but still maintains the
offset to keep in parity with the original c lib.  So the leading zero
values implied in the result set in the docs is actually an exercise for
the coder for implying an offset.  As far as changes to the output, im
fairly confident in the output integrity, barring precision loss related to
dealing with float64/c.double (c.TI_REAL) in general,  as the go bindings
do little more than throw the inputs provided directly at the function
pointers supplied via indicator_index.c for a given indicator name.


Re: solving the offset problem, Id be happy to update the readme, or
discuss the ramifications of filling in zeroes for the 'warmup indices'
(which im somewhat hesitant to do at the moment given a use case ive got
with using indicators on a rolling subset of data).

**Comment by mcardinalupgrade** [comment]
So how do you determine how many zeros need to be stripped at the end of the result set from technicalviking/tulipindicators to get the last useful value?

**Comment by marccardinal** [comment]
So how do you determine how many zeros need to be stripped at the end of the result set from technicalviking/tulipindicators to get the last useful value?

**Comment by Code-exE-Software** [comment]
I'm not sure I understand your question.  The C lib underneath doesn't truncate values from the end of the output list (that I'm aware of), but rather refrains from even starting the list until after the 'offset' has been passed.  As another example, the Bollinger Band indicator has an offset equal to the period - 1.  So given 100 inputs and a period of 20, you should get an output slice with a length of 81 (100 - (20 - 1))   The first of these output values will align with the 20th input, and the final input will align with the final output.

However, in the intervening time since I last addressed issues with this library, I've discovered multiple implementations of indicators involve mathematical shortcuts that aren't.  (Again, case in point, the Bollinger Bands).  In an effort to fix that, when I have time, I'll be making a branch of this lib to reimplement the indicators purely in go, eliminating the shortcuts in the C lib that I've tripped over.

As it is, currently this lib is rather blindly trusting that the underlying c files have correct implementations of the various indicator methods, and in cases where that's not true, I'll have to dig into it.
